export const Months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const FooterLinks = [
  { title: 'About', link: '/' },
  { title: 'Help Center', link: '/' },
  { title: 'Terms of Service', link: '/' },
  { title: 'Privacy Policy', link: '/' },
  { title: 'Cookie Policy', link: '/' },
  { title: 'Ads info', link: '/' },
  { title: 'Blog', link: '/' },
  { title: 'Status', link: '/' },
  { title: 'Carrres', link: '/' },
  { title: 'Brand Resources', link: '/' },
  { title: 'Advertsing', link: '/' },
  { title: 'Marketing', link: '/' },
  { title: 'Twitter for Business', link: '/' },
  { title: 'Developers', link: '/' },
  { title: 'Directory', link: '/' },
  { title: 'Settings', link: '/' },
];
