export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const UPDATE_POST_LIKES_REQUEST = 'UPDATE_POST_LIKES_REQUEST';
export const UPDATE_POST_LIKES_SUCCESS = 'UPDATE_POST_LIKES_SUCCESS';
export const UPDATE_POST_LIKES_FAILURE = 'UPDATE_POST_LIKES_FAILURE';
